<div class="page-title">
	<h1>FAQ</h1>
</div><!-- end page title -->
<div class="faq-page-wrapper">
	<div class="topics-wrapper">
		<div class="topics-left">
			<h2 class="topics-header">For Customers</h2>
			<h4 class="pixafy-tab-trigger faq-title" data-tab-container="faq-orders">Orders</h4>
			<h4 class="pixafy-tab-trigger faq-title" data-tab-container="faq-returns">Returns</h4>
			<h4 class="pixafy-tab-trigger faq-title" data-tab-container="faq-shipping">Shipping</h4>
			<h4 class="pixafy-tab-trigger faq-title" data-tab-container="faq-voting">Voting</h4>
			<h4 class="pixafy-tab-trigger faq-title" data-tab-container="faq-pm">Product &amp; Manufacturing</h4>
			<h4 class="pixafy-tab-trigger faq-title" data-tab-container="faq-pp">Payment &amp; Pricing</h4>
			<h4 class="pixafy-tab-trigger faq-title" data-tab-container="faq-security">Security</h4>
			<h4 class="pixafy-tab-trigger faq-title" data-tab-container="faq-myaccount">My Account</h4>
			<h4 class="pixafy-tab-trigger faq-title" data-tab-container="faq-contact-customer">Contact Us</h4>
		</div><!-- end topics-left -->

		<div class="topics-right">
			<h2 class="topics-header">For Designers</h2>
			<h4 class="pixafy-tab-trigger faq-title" data-tab-container="faq-hiw">How It Works<h4/>
			<h4 class="pixafy-tab-trigger faq-title" data-tab-container="faq-submissions">Submissions</h4>
			<h4 class="pixafy-tab-trigger faq-title" data-tab-container="faq-vw">Voting &amp; Winning</h4>
			<h4 class="pixafy-tab-trigger faq-title" data-tab-container="faq-rc">Rights &amp; Contracts</h4>
			<h4 class="pixafy-tab-trigger faq-title" data-tab-container="faq-sp">Sales &amp; Payment</h4>
			<h4 class="pixafy-tab-trigger faq-title" data-tab-container="faq-dp">Designer Profile</h4>
			<h4 class="pixafy-tab-trigger faq-title" data-tab-container="faq-contact-designer">Contact Us</h4>
		</div><!-- end topics right -->
	</div><!-- end topics wrapper -->

	<div class="answers-wrapper">
		<div class="pixafy-tab-container" id="faq-orders">
			<h4 class="faq-title">Orders</h4>
			<div class="pixafy-accordian-group" data-accordian-id="faq-orders">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faq-customer-orders')->toHtml() ?>
			</div>
		</div>
		<div class="pixafy-tab-container" id="faq-returns">
			<h4 class="faq-title">Returns</h4>
			<div class="pixafy-accordian-group" data-accordian-id="faq-returns">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faq-customer-returns')->toHtml() ?>
			</div>
		</div>
		<div class="pixafy-tab-container" id="faq-shipping">
			<h4 class="faq-title">Shipping</h4>
			<div class="pixafy-accordian-group" data-accordian-id="faq-shipping">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faq-customer-shipping')->toHtml() ?>
			</div>
		</div>
		<div class="pixafy-tab-container" id="faq-voting">
			<h4 class="faq-title">Voting</h4>
			<div class="pixafy-accordian-group" data-accordian-id="faq-voting">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faq-customer-voting')->toHtml() ?>
			</div>
		</div>
		<div class="pixafy-tab-container" id="faq-pm">
			<h4 class="faq-title">Product &amp; Manufacturing</h4>
			<div class="pixafy-accordian-group" data-accordian-id="faq-pm">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faq-customer-pm')->toHtml() ?>
			</div>
		</div>
		<div class="pixafy-tab-container" id="faq-pp">
			<h4 class="faq-title">Payment &amp; Pricing</h4>
			<div class="pixafy-accordian-group" data-accordian-id="faq-pp">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faq-customer-pp')->toHtml() ?>
			</div>
		</div>
		<div class="pixafy-tab-container" id="faq-security">
			<h4 class="faq-title">Security</h4>
			<div class="pixafy-accordian-group" data-accordian-id="faq-security">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faq-customer-security')->toHtml() ?>
			</div>
		</div>
		<div class="pixafy-tab-container" id="faq-myaccount">
			<h4 class="faq-title">My Account</h4>
			<div class="pixafy-accordian-group" data-accordian-id="faq-myaccount">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faq-customer-myaccount')->toHtml() ?>
			</div>
		</div>
		<div class="pixafy-tab-container" id="faq-contact-customer">
			<h4 class="faq-title">Contact Us - Customer</h4>
			<div class="pixafy-accordian-group" data-accordian-id="faq-contact-customer">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faq-customer-contact')->toHtml() ?>
			</div>
		</div>
		<div class="pixafy-tab-container" id="faq-hiw">
			<h4 class="faq-title">How It Works</h4>
			<div class="pixafy-accordian-group" data-accordian-id="faq-hiw">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faq-designer-hiw')->toHtml() ?>
			</div>
		</div>
		<div class="pixafy-tab-container" id="faq-submissions">
			<h4 class="faq-title">Submissions</h4>
			<div class="pixafy-accordian-group" data-accordian-id="faq-submissions">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faq-designer-submissions')->toHtml() ?>
			</div>
		</div>
		<div class="pixafy-tab-container" id="faq-vw">
			<h4 class="faq-title">Voting &amp; Winning</h4>
			<div class="pixafy-accordian-group" data-accordian-id="faq-vw">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faq-designer-vw')->toHtml() ?>
			</div>
		</div>
		<div class="pixafy-tab-container" id="faq-rc">
			<h4 class="faq-title">Rights &amp; Contracts</h4>
			<div class="pixafy-accordian-group" data-accordian-id="faq-rc">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faq-designer-rc')->toHtml() ?>
			</div>
		</div>
		<div class="pixafy-tab-container" id="faq-sp">
			<h4 class="faq-title">Sales &amp; Payment</h4>
			<div class="pixafy-accordian-group" data-accordian-id="faq-sp">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faq-designer-sp')->toHtml() ?>
			</div>
		</div>
		<div class="pixafy-tab-container" id="faq-dp">
			<h4 class="faq-title">Designer Profile</h4>
			<div class="pixafy-accordian-group" data-accordian-id="faq-dp">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faq-designer-dp')->toHtml() ?>
			</div>
		</div>
		<div class="pixafy-tab-container" id="faq-contact-designer">
			<h4 class="faq-title">Contact Us - Designers</h4>
			<div class="pixafy-accordian-group" data-accordian-id="faq-contact-designer">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('faq-designer-contact')->toHtml() ?>
			</div>
		</div>
	</div>
</div>

<script>
	(function( $, window, document ) {
			$(function() {
				var hash = window.location.hash;
				if ( hash === '#returns' ) {
					$( 'h4[data-tab-container="faq-returns"]' ).trigger( 'click' );
					$( '.pixafy-accordian-group[data-accordian-id="faq-returns"]' )
						.find( 'h2' )
						.first()
						.trigger( 'click' );
				}
			});
	})( jQuery, window, document, undefined );
</script>