<?php $skinPath = $this->getSkinUrl();?>
<link rel="stylesheet" type="text/css" href="<?php echo $skinPath.'css/press.css?v=1.0'; ?>" media="all" />
<link rel="stylesheet" type="text/css" href="/js/fancybox/jquery.fancybox.css" media="all" />
<script type="text/javascript" src="/js/scripts.js?v=1.6"></script>
<script type="text/javascript" src="/js/fancybox/jquery.fancybox.pack.js"></script>


<div class="press-section">
    <h2>In The Press</h2>
    <div class="content-wrapper">
        <p>For press inquiries, please contact B'squared Public Relations<br/>Email: <a href="mailto:bcohen@bsquaredpr.com">bcohen@bsquaredpr.com</a> Phone 212.265.3313.</p>
    </div>
    <div class="content-wrapper">
        <h3>News & Magazines</h3>
        <ul class="press_labels">
            <li>
                <a class="press_label" href="#instyle_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/instyle_logo.png') ?>" alt="InStyle">
                    <a id="instyle_screenshot" class="press_hidden" href="http://news.instyle.com/2013/03/13/jewelry-shopping-site-shopbevel/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/instyle.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#fashionista_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/fashionista_logo.png') ?>" alt="Fashionista">
                    <a id="fashionista_screenshot" class="press_hidden" href="http://fashionista.com/2013/03/e-commerce-startup-shop-bevel/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/fashionista.png') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#cbs_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/cbs_logo.png') ?>" alt="CBS">
                    <a id="cbs_screenshot" class="press_hidden" href="http://www.cbsatlanta.com/video?autoStart=true&topVideoCatNo=default&clipId=8685641" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/cbs.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#martha_stewart_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/martha_stewart_logo.png') ?>" alt="Martha Stewart">
                    <a id="martha_stewart_screenshot" class="press_hidden" href="https://sphotos-a.xx.fbcdn.net/hphotos-ash3/535622_525062907546377_350497965_n.jpg" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/martha_stewart.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#people_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/people_logo.png') ?>" alt="People">
                    <a id="people_screenshot" class="press_hidden" href="#">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/people.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#cbs2_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/cbs_logo.png') ?>" alt="CBS">
                    <a id="cbs2_screenshot" class="press_hidden" href="http://newyork.cbslocal.com/video/8434724-eye-on-new-york-whats-hot-and-how-to-wear-it/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/cbs2.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#pando_daily_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/pando_daily_logo.png') ?>" alt="PandoDaily">
                    <a id="pando_daily_screenshot" class="press_hidden" href="http://pandodaily.com/2013/03/20/shopbevel-launches-threadless-for-jewelry-site-with-seed-investment-from-lightbank-great-oaks/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/pando_daily.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#twc_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/twc_logo.png') ?>" alt="TWC">
                    <a id="twc_screenshot" class="press_hidden" href="http://thirdwavefashion.com/2013/03/watch-out-wednesday-shopbevel/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/twc.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#today_show_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/today_logo.png') ?>" alt="Today Show">
                    <a id="today_show_screenshot" class="press_hidden" href="http://www.today.com/style/spring-style-10-things-try-month-1C9145346" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/today_show.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#real_simple_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/real_simple_logo.png') ?>" alt="Real Simple">
                    <a id="real_simple_screenshot" class="press_hidden" href="http://simplystated.realsimple.com/2013/03/06/shop-bevel-crowdsourced-jewelry/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/real_simple.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
        </ul>
    </div>
    <div class="content-wrapper">
        <h3>Blogosphere</h3>
        <ul class="press_labels">
            <li>
                <a class="press_label" href="#ever_so_popular_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/ever_popular_logo.png') ?>" alt="Ever So Popular">
                    <a id="ever_so_popular_screenshot" class="press_hidden" href="http://instagram.com/p/VzK4XbHLEy/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/ever_so_popular.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#corgis_and_cocktails_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/corgis_and_cocktails_logo.png') ?>" alt="Of Corgis and Cocktails">
                    <a id="corgis_and_cocktails_screenshot" class="press_hidden" href="http://www.ofcorgisandcocktails.com/2013/03/the-birds-eye.html" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/corgis_and_cocktails.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#champagne_picnic_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/champagne_picnic_logo.png') ?>" alt="Champagne Picnic">
                    <a id="champagne_picnic_screenshot" class="press_hidden" href="http://instagram.com/p/WzYo5mmn9b/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/champagne_picnic.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#caitlin_burke_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/caitlin_burke_logo.png') ?>" alt="Caitlin Burke">
                    <a id="caitlin_burke_screenshot" class="press_hidden" href="http://instagram.com/p/We5YZol3bN/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/caitlin_burke.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#style_santina_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/style_santina_logo.png') ?>" alt="Style by Santina">
                    <a id="style_santina_screenshot" class="press_hidden" href="http://instagram.com/p/XaAvTmhEDj/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/style_santina.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#advice_twenty_something_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/advice_twenty_something_logo.png') ?>" alt="Advice from a Twenty Something">
                    <a id="advice_twenty_something_screenshot" class="press_hidden" href="http://instagram.com/p/WU-vCsMEt7/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/advice_twenty_something.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#lace_tulle_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/lace_tulle_logo.png') ?>" alt="Lace and Tulle">
                    <a id="lace_tulle_screenshot" class="press_hidden" href="https://twitter.com/laceandtulle_/status/304594785262510081/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/lace_tulle.jpeg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#makeup_freeek_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/makeup_freeek_logo.png') ?>" alt="Makeup Freeek">
                    <a id="makeup_freeek_screenshot" class="press_hidden" href="http://instagram.com/p/WPT5rmmrc3/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/makeup_freeek.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#peach_gingham_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/peach_gingham_logo.png') ?>" alt="Peach Gingham">
                    <a id="peach_gingham_screenshot" class="press_hidden" href="http://instagram.com/p/WRi2RJwiCs/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/peach_gingham.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#perpetuity_style_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/perpetuity_style_logo.png') ?>" alt="Perpetuity Style">
                    <a id="perpetuity_style_screenshot" class="press_hidden" href="http://www.perpetuitystyle.com/2013/02/what-i-wore.html" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/perpetuity_style.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#style_mayvin_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/style_mayvin_logo.png') ?>" alt="Style Mayvin">
                    <a id="style_mayvin_screenshot" class="press_hidden" href="https://twitter.com/therealtstrong/status/300839015643488257/photo/1" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/style_mayvin.jpeg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#style_on_line_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/style_on_line_logo.png') ?>" alt="Style on the Line">
                    <a id="style_on_line_screenshot" class="press_hidden" href="http://instagram.com/p/V7DS-ewgHW/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/style_on_line.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#fashion_beauty_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/fashion_beauty_logo.png') ?>" alt="Huffington Post: Fashion & Beauty">
                    <a id="fashion_beauty_screenshot" class="press_hidden" href="http://instagram.com/p/VnJ_5tCzbz/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/fashion_beauty.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#la_vie_en_liz_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/la_vie_en_liz_logo.png') ?>" alt="La Vie En Liz">
                    <a id="la_vie_en_liz_screenshot" class="press_hidden" href="http://instagram.com/p/V4neQ-NMq3/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/la_vie_en_liz.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
            <li>
                <a class="press_label" href="#jennif_hsieh_screenshot" rel="1">
                    <img src="<?php echo $this->getSkinUrl('images/press/logos/jennif_hsieh_logo.png') ?>" alt="Jennif Hsieh">
                    <a id="jennif_hsieh_screenshot" class="press_hidden" href="http://instagram.com/p/VrrpgRgpiH/" target="_blank">
                        <img src="<?php echo $this->getSkinUrl('images/press/screenshots/jennif_hsieh.jpg') ?>" alt="">
                    </a>
                </a>
            </li>
        </ul>
    </div>
</div>