
<script type="text/javascript">
	function ajaxPostFuncOne2(param){
		jQuery.ajax({
			type: "GET",
			url: "<?php echo $this->getUrl('registeration/ajax/pageeight/')?>",
			dataType: "json",
			success: function(jsonResponse){
	         	if(jsonResponse.status == 1){
		         	jQuery("#ajax-content").html(jsonResponse.html_content);
	         	}else{
		         	alert(jsonResponse.error_message);
	         	}
	        }
					
		});
	}
</script>

<h1>Registeration Page 8</h1>
<P>you are # <?php echo Mage::getsingleton('core/session')->getWaitlistRank($link);?> on the list</P>
<P>link: <?php echo Mage::getsingleton('core/session')->getUniqueLink($link);?></P>
<input class="ipt-footerSubmit" type="submit" value="See trunk shows" onclick="ajaxPostFuncOne2()"></input>				
